Test the dependecy programs are installed and available before using then
This will prevent extra erro output being shown.

diff --git a/ga b/ga
--- a/ga
+++ b/ga
@@ -12,10 +12,12 @@ usage() {
 }
 
 encrypt() {
-     echo "$1" | openssl enc -aes-128-cbc -a -salt -pass pass:$2 | tr -d "\n"
+    hash openssl 2>/dev/null || { echo >&2 "openssl is require but it's not installed.  Aborting."; exit 1; }
+    echo "$1" | openssl enc -aes-128-cbc -a -salt -pass pass:$2 | tr -d "\n"
 }
 
 decrypt() {
+    hash openssl 2>/dev/null || { echo >&2 "openssl is require but it's not installed.  Aborting."; exit 1; }
     echo "$1" | openssl enc -aes-128-cbc -a -d -salt -pass pass:$2
 }
 
@@ -26,6 +28,8 @@ getsalt() {
 }
 
 calculate() {
+    hash oathtool 2>/dev/null || { echo >&2 "oathtool is require but it's not installed.  Aborting."; exit 1; }
+
     service=$1
     key=$2
     if [ -z "$service" ] || [ -z "$key" ]; then
@@ -66,6 +70,7 @@ while getopts "a:c:lqs" flag; do
             done < ${OATHKEYFILE}
             ;;
         q)
+            hash qrencode 2>/dev/null || { echo >&2 "qrencode is require but it's not installed.  Aborting."; exit 1; }
             filter=$2
             salt=${GSALT:-$(getsalt)}
             while read -r line
